### ISSUE TITLE
Advanced search using the MUST (+) operator searches for OR instead of AND

### ISSUE THREAD

**Issue by DavidIB** [STEPBible/step#36]
If you use Advanced Search to search for "all of the words", the correct syntax is created but when the search is performed the syntax is lost. 
eg find every place where "all the words" "Jesus" and "tables" occur together. The correct syntax is:
t= +Jesus +tables
The URL created is: www.stepbible.org/?q=version=ESV|syntax=t= +Jesus +tables
But hovering over the roundle indicates that the search is "t=  Jesus  tables"
![image](https://user-images.githubusercontent.com/1691834/69573543-3aa02c80-0fbe-11ea-8035-70399c12f70f.png)

I suspect that when the URL is interpreted, the "+" is changed to a space

**Comment by DavidIB** [comment]
I suppose the easiest way round this is to use "AND" instead of "+"

**Comment by patricksptang** [comment]
This problem is probably obsoleted.
