### ISSUE TITLE
Book/chapter selection button

### ISSUE THREAD

**Issue by DavidIB** [STEPBible/step#40]
The issue is twofold: 
1) Some new users find it difficult to work out how to select a chapter. 
2) Some people prefer to point and click rather than typing. 
Of course, anyone can click on the visible ref (eg [Gen 1 ] ) and get a series of dropdowns by which to pick a book chapter. However, this relies on server calls, so it can be slow - esp on mobile devices. (using www.STEPBible.org is still useful on mobile devices cos it has a different feature set to the App). 

One solution to both of these is a button that creates a URL to change the chapter. 
OR (better) creates a call to change the chapter in the selected Panel 

In order to do this without calling the server, it is prob easiest to show ALL Bible chapters with a link to each chapter. The chapters would want to be hidden till the user clicks on the book. (Note, we can't use hover to unhide cos this won't work on Mobile). 

At the same time, it is prob worth adding something to pick a Bible. If this isn't going to rely on a server call, we'll want to include only a subset of Bibles - perhaps the ones marked as "Most widely used" (though this list is in need of revision). A link at the end to "more" could take them to the full list on the server. 

Visually, I'm not sure what it would look like - perhaps something like: 
![image](https://user-images.githubusercontent.com/1691834/71834172-7858a080-30a6-11ea-9b94-34851800360c.png)

**Comment by patricksptang** [comment]
We implemented a new UI over a year ago.
